# Generated by Django 5.1.2 on 2024-11-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topis',
            new_name='Topic',
        ),
    ]
